#Define the service running port

#I commented the running port because of discovery service and need to running multiple instances of each service
#server:
#  port: 9197


#Create database for particular service
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dbTreatment?createDatabaseIfNotExist=true
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver

