#Define the service running port
server:
  port: 9195

#Create database for particular service
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dbMedicine?createDatabaseIfNotExist=true
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver

