#Define the service running port
server:
  port: 9193

#Create database for particular service
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dbDoctor?createDatabaseIfNotExist=true
    username: root
    password: 
    driver-class-name: com.mysql.jdbc.Driver

